### ISSUE TITLE
Document process of switching from generic theme to GC theme

### ISSUE THREAD

**Issue by mgifford** [drupalwxt/wxt#196]
It isn't clear in the documentation how to switch from the generic design, such as you get here:
  https://drupalwxt.github.io/

And the default GC theme, such as you get here:
  https://open.canada.ca/en

I remember there being a simple toggle or something somewhere in the D7 theme, but am not sure where that is in D8.  Either way it needs to be documented.

**Comment by zachomedia** [comment]
I think you might mean this section which we documented in the starterkit?

https://github.com/drupalwxt/wxt_bootstrap/tree/8.x-1.x/starterkits/wxt

This script is something we also use for subtheme that might do most of the configuration for you:

```php
/**
 * Implements hook_install().
 */
function canada_core_install() {
  $theme_list = [
    'claro',
    'canada_experiments',
  ];

  // Install themes.
  \Drupal::service('theme_installer')->install($theme_list);

  // Get theme manager
  $system_theme = \Drupal::configFactory()->getEditable('system.theme');

  // Set default and admin themes.
  $system_theme
    ->set('default', 'canada_experiments')
    ->set('admin', 'claro')
    ->save();

  // GCWeb
  $config = \Drupal::configFactory()->getEditable('wxt_library.settings');
  $config->set('wxt.theme', 'theme-gcweb');
  $config->save();
}
```

And for the library itself which is linked above can just add this to config/install/wxt_library.settings.yml for your custom module

```yaml
url:
  visibility: 0
  pages:
    - 'admin*'
    - 'imagebrowser*'
    - 'img_assist*'
    - 'imce*'
    - 'node/add/*'
    - 'node/*/edit'
    - 'print/*'
    - 'printpdf/*'
    - system/ajax
    - 'system/ajax/*'
    - 'admin*'
    - 'imagebrowser*'
    - 'img_assist*'
    - 'imce*'
    - 'node/add/*'
    - 'node/*/edit'
    - 'print/*'
    - 'printpdf/*'
    - system/ajax
    - 'system/ajax/*'
theme:
  visibility: 1
  themes:
    canada_experiments: canada_experiments
    wxt_bootstrap: wxt_bootstrap
minimized:
  options: 1
files:
  types:
    css: css
    js: js
wxt:
  theme: theme-gcweb
```
